bookstore/books/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from books import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
]

bookstore/bookstore/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^user/',include('users.urls',namespace='user')),
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/',include('tinymce.urls')),
    url(r'^',include('books.urls',namespace='books')),
]

bookstore/users/urls.py
from django.conf.urls import url
from django.contrib import admin
from users import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^register_handle/$',views.register_handle,name='register_handle'),#用户注册
    url(r'^login/$',views.login,name='login'),
    url(r'^login_check/$',view.login_check,name='login_check'),
]

bookstore/books/models.py
from django.db import models
from tinymce.models import HTMLField
from db.base_model import BaseModel
from books.enums import *
# Create your models here.

class BooksManager(models.Manager):
    def get_books_by_type(self,type_id,limit=None,sort='default'):
        if sort =='new':
            order_by = ('-create_time',)
        elif sort == 'hot':
            order_by = ('-sales',)
        elif sort == 'price':
            order_by = ('price',)
        else:
            order_by = ('-pk',)

        books_li = self.filter(type_id = type_id).order_by(*order_by)
        
        if limit:
            books_li = books_li[:limit]
        return books_li
    def get_books_by_id(self,books_id):
        try:
            books = self.get(id = books_id)
        except self.model.DoesNotExist:
            books = None
        return books

class Books(BaseModel):
    books_type_choices = ((k,v)for k,v in BOOKS_TYPE.items())
    status_choices = ((k,v) for k,v in STATUS_CHOICE.items())
    type_id = models.SmallIntegerField(default=PYTHON,choices=books_type_choices,verbose_name='商品种类')
    name = models.CharField(max_length=20, verbose_name='商品名称')
    desc = models.CharField(max_length=128,verbose_name ='商品简介')
    price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name ='商品价格')
    unit = models.CharField(max_length=20,verbose_name='商品单位')
    stock = models.IntegerField(default=1,verbose_name='商品库存')
    sales = models.IntegerField(default=0,verbose_name='商品销量')
    detail = HTMLField(verbose_name='商品详情')
    image = models.ImageField(upload_to='books',verbose_name = '商品图片')
    status = models.SmallIntegerField(default=ONLINE,choices=status_choices,verbose_name='商品状态')

    objects = BooksManager()
    
    def __str__():
        return self.name

    class Meta:
        db_table = 's_books'
        verbose_name = '书籍'
        verbose_name_plural = '书籍'

bookstore/users/models.py
from django.db import models
from db.base_model import BaseModel
from utils.get_hash import get_hash
# Create your models here.
class PassportManager(models.Manager):
    def add_one_passport(self,password,email):
        passport = self.create(username=username,password=get_hash(password),email=email)
        return passport
    
    def get_one_passport(self,username,password):
        try:
            passport = self.get(username=username,password=get_hash(password))
        except self.model.DoesNotExist:
            
            passport = None
        return passport

class Passport(BaseModel):
    username = models.CharField(verbose_name='用户名称',max_length=20,unique=True)
    password = models.CharField(verbose_name='用户密码',max_length=20)
    email = models.EmailField(verbose_name='用户邮箱')
    is_active = models.BooleanField(default=False,verbose_name='激活状态')
    
    #用户表的管理器
    objects = PassportManager()

    class Meta:
        db_table = 's_user_account'

bookstore/books/views.py
from django.shortcuts import render
from books.models import Books
from books.enums import *
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
# Create your views here.

def index(request):
    python_new = Books.objects.get_books_by_type(PYTHON,limit=3,sort='new')
    
    python_hot = Books.objects.get_books_by_type(PYTHON,limit=4,sort='hot')

    javascript_new = Books.objects.get_books_by_type(JAVASCRIPT,limit=3,sort='new')

    javascript_hot = Books.objects.get_books_by_type(JAVASCRIPT,limit=4,sort='hot')

    algorithms_new = Books.objects.get_books_by_type(ALGORITHMS,limit=3,sort='new')

    algorithms_hot = Books.objects.get_books_by_type(ALGORITHMS,limit=4,sort='hot')

    machinelearning_new = Books.objects.get_books_by_type(MACHINELEARNING,limit=3,sort='new')

    machinelearning_hot = Books.objects.get_books_by_type(MACHINELEARNING,limit=4,sort='hot')

    operatingsystem_new = Books.objects.get_books_by_type(OPERATINGSYSTEM,limit=3,sort='new')

    operatingsystem_hot = Books.objects.get_books_by_type(OPERATINGSYSTEM,limit=4,sort='hot')

    database_new = Books.objects.get_books_by_type(DATABASE,limit=3,sort='new')

    database_hot = Books.objects.get_books_by_type(DATABASE,limit=4,sort='hot')
    
    context = {
        'python_new':python_new,
        'python_hot':python_hot,
        'javascript_new':javascript_new,
        'javascript_hot':javascript_hot,
        'algorithms_new':algorithms_new,
        'algorithms_hot':algorithms_hot,
        'machinelearning_new':machinelearning_new,
        'machinelearning_hot':machinelearning_hot,
        'operatingsystem_new':operatingsystem_new,
        'operatingsystem_hot':operatingsystem_hot,
        'database_new':database_new,
        'database_hot':database_hot,
    }
    
    return render(request,'books/index.html',context)

bookstore/users/views.py
from django.shortcuts import render

# Create your views here.
def register(request):
    return render(request, 'users/register.html')


def register_handle(request):
    username = request.POST.get('user_name'),
    password = request.POST.get('pwd'),
    email = request.POST.get('email')
    
    #进行数据校验
    if not all([username,password,email]):
        return render(request,'users/register.html',{
                'errmsg':'参数不能为空!'
                })
    #判断邮箱是否合法
    if not re.match(r'^^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$',email):
        return render(request,'users/register.html',{
                'errmsg':'邮箱不合法！'
                })
    #进行业务处理，注册，向帐户系统中添加帐户
    try:
        Passport.objects.add_one_passport(username=username,password=password,email=email)
    except:
        return render(request,'users/register.html',{
                'errmsg':'用户已存在！'
                })

    return redirect(reverse('books:index'))


def login(request):
    if request.COOKIES.get("username"):
        username= request.COOKIES.get("username")
        checked = 'checked'
    else:
        username = ''
        checked = ''
    context = {
        'username':username,
        'checked':checked,
    }
    return render(request,'users/login.html',context)

def login_check(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    remember = request.POST.get('remember')

    if not all([username,password,remember]):
        return JsonResponse({'res':2})

    passport = Passport.objects.get_one_passport(username=username,password=password)
    if passport:
        next_url = reverse('books:index')
        jres = JsonResponse({'res':1,'next_url':next_url})

        if remember == 'true':

            jres.set_cookie('username',username,max_age=7*24*3600)
        else:
            jres.delete_cookie('username')

        request.session['islogin'] = True
        request.session['username'] = username
        request.session['passport_id'] = passport.id
        return jres
    else:
        return JsonResponse({'res':0})
        

bookstore/templates/books/index.html
    {% load staticfiles %}
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>尚硅谷书城-首页</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css'  %}">
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
 <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到尚硅谷书城!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png" style="width: 160px; height: 53px;"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="book_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">移动端书城</a></li>
				<li class="interval">|</li>
				<li><a href="">秒杀</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="python">Python</a></li>
			<li><a href="#model02" class="javascript">Javascript</a></li>
			<li><a href="#model03" class="algorithms">数据结构与算法</a></li>
			<li><a href="#model04" class="machinelearning">机器学习</a></li>
			<li><a href="#model05" class="operatingsystem">操作系统</a></li>
			<li><a href="#model06" class="database">数据库</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="images/slide.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="images/slide02.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="images/slide03.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
				<li><img src="images/slide04.jpg" alt="幻灯片" style="width: 760px; height: 270px;"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="{% static 'images/adv01.jpg' %}" style="width: 240px; height: 135px;"></a>
			<a href="#"><img src="{% static 'images/adv02.jpg' %}" style="width: 240px; height: 135px;"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">Python</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for book in python_new %}
                <a href='#'>{{ book.name }}</a>
                {% endfor %}
		</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="{% static 'images/banner01.jpg' %}"></div>
			<ul class="book_list fl">
            {% for book in python_hot %}
				<li>
					<h4><a href="#">{{ book.name }}</a></h4>
                    <a href='#'><img src='{% static book.image %}'></a>
                    <div class='prize'>￥{{ book.price }}</div>
		        </li>
		    {% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">Javascript</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">Javascript高级编程</a>
				<a href="#">Javascript语言精粹</a>				
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="images/banner02.jpg"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">Javascript高级程序设计</a></h4>
					<a href="#"><img src="images/book/book005.jpg"></a>
					<div class="prize">¥ 48.00</div>
				</li>
				<li>
					<h4><a href="#">Javascript权威指南</a></h4>
					<a href="#"><img src="images/book/book006.jpg"></a>
					<div class="prize">¥ 46.00</div>
				</li>
				<li>
					<h4><a href="#">Javascript语言精粹</a></h4>
					<a href="#"><img src="images/book/book007.jpg"></a>
					<div class="prize">¥ 19.00</div>
				</li>
				<li>
					<h4><a href="#">Javascript DOM编程艺术</a></h4>
					<a href="#"><img src="images/book/book008.jpg"></a>
					<div class="prize">¥ 25.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">数据结构与算法</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">算法导论</a>
				<a href="#">数据结构与算法分析</a>
				<a href="#">计算机程序设计艺术</a>
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="images/banner03.jpg"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">数据结构与算法分析</a></h4>
					<a href="#"><img src="images/book/book009.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">算法导论</a></h4>
					<a href="#"><img src="images/book/book010.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">算法</a></h4>
					<a href="#"><img src="images/book/book011.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">计算机程序设计艺术</a></h4>
					<a href="#"><img src="images/book/book012.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">机器学习</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">机器学习</a>
				<a href="#">统计学习方法</a>
				<a href="#">集体智慧编程</a>
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="images/banner04.jpg"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">机器学习</a></h4>
					<a href="#"><img src="images/book/book013.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">机器学习实战</a></h4>
					<a href="#"><img src="images/book/book014.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">统计学习方法</a></h4>
					<a href="#"><img src="images/book/book015.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">集体智慧编程</a></h4>
					<a href="#"><img src="images/book/book016.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">操作系统</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">UNIX环境高级编程</a>
				<a href="#">深入理解计算机系统</a>
				<a href="#">现代操作系统</a>
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="images/banner05.jpg"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">现代操作系统</a></h4>
					<a href="#"><img src="images/book/book017.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">深入理解计算机系统</a></h4>
					<a href="#"><img src="images/book/book018.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">UNIX环境高级编程</a></h4>
					<a href="#"><img src="images/book/book019.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">鸟哥的私房菜</a></h4>
					<a href="#"><img src="images/book/book020.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">数据库</h3>
			<div class="subtitle fl">
				<span>|</span>
				<a href="#">数据库系统概念</a>
				<a href="#">高性能MySQL</a>
				<a href="#">MySQL必知必会</a>
			</div>
			<a href="#" class="book_more fr">查看更多 ></a>
		</div>

		<div class="book_con clearfix">
			<div class="book_banner fl"><img src="images/banner06.jpg"></div>
			<ul class="book_list fl">
				<li>
					<h4><a href="#">数据库系统概念</a></h4>
					<a href="#"><img src="images/book/book021.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">高性能MySQL</a></h4>
					<a href="#"><img src="images/book/book022.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">Redis实战</a></h4>
					<a href="#"><img src="images/book/book023.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
				<li>
					<h4><a href="#">Redis设计与实现</a></h4>
					<a href="#"><img src="images/book/book024.jpg"></a>
					<div class="prize">¥ 38.00</div>
				</li>
			</ul>
		</div>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京尚硅谷信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
</body>
</html>

bookstore/templates/users/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>尚硅谷书城-登录</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
    $(function(){
        $('#btnLogin').click(function(){
            var username = $("#username").val()
            var password = $("#pwd").val()
            var remember = $('input[name="rememeber"]').prop('checked')
            var csrfmiddlewaretoken = $('input[name="csrfmiddlewaretoken"]').val()
            var params = {
                username:username,
                password:password,
                remember:remember,
                csrfmiddlewaretoken:csrfmiddlewaretoken
            }
            $.post('/user/login_check/',params,function(data){
                    if(data.res==1){
                        location.href = data.next_url;
                    }else if(data.res==2){
                        alert("数据不完整");
                    }else if(data.res==0){
                        alert("用户名和密码错误");
                    }
                    
                    })
                
                })
            
            })
    </script>
</head>
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="images/logo.png" style="width: 160px; height: 53px;"></a>	
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">学计算机 · 来尚硅谷</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="#">立即注册</a>
				</div>
				<div class="form_input">
                {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="button" name="" value="登录" class="input_submit">
					
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京尚硅谷信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

bookstore/templates/users/register.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>尚硅谷书城-注册</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/register.js"></script>
</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo.png" style="width: 160px; height: 53px;"></a>
			<div class="reg_slogan">学计算机  ·  来尚硅谷</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="#">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action='{% url 'user:register_handle' %}' method='post' >
                {% csrf_token %}
                <ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”尚硅谷书城用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
                    {{ errmsg }}
				</ul>
				</form>
			</div>

		</div>

	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京尚硅谷信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>